# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Natalie Hofmeister
description:      'PhD Candidate'
url:              https://nathofme.github.io
baseurl:          /

author:
  name:           'Natalie Hofmeister'
  url:            https://twitter.com/nathofme

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
